### ISSUE TITLE
Add docs for setting GOBIN before installing granitic support tools

### ISSUE THREAD

**Issue by AbhijetPokhrel** [graniticio/granitic#41]
GOBIN variables is necessary while installing binaries to binary file location. If user does not have the GOBIN path set then the support tools docs will not work.

**Comment by benhalstead** [comment]
Thanks very much for raising this.

Could I ask which OS this relates to and how you installed Go (e.g from an installer package)? My understanding is that GOBIN doesn't need to be set as long as

1. GOPATH is set
2. GOPATH contains a folder called bin with appropriate permissions

**Comment by AbhijetPokhrel** [comment]
hi @benhalstead 

I installed vai pkg downloaded from official go docs. https://golang.org/dl/
I have set my GOPATH as well. Just found that the grnc-project and grnc-bind commands were not working when my GOBIN was not set.

OS: MacOS 10.14.6
go version go1.13.1 darwin/amd64

**Comment by benhalstead** [comment]
Added troubleshooting section to installation instructions
