### ISSUE TITLE
Format application log entries as JSON

### ISSUE THREAD

**Issue by benhalstead** [graniticio/granitic#53]
Many log processing tools require that (or work best when)  each entry is formatted as a JSON fragment. This issue proposes adding JSON application logging support to Granitic.

## New configuration values:

**LogWriting.Entry** 

Can be set to "TEXT" or "JSON" (defaults to "TEXT"). Controls whether each log entry is a single line of text or wrapped in a JSON fragment.

**LogWriting.Format.JSON.Prefix**

A string written before each entry in the output file/stdout defaults to ""

**LogWriting.Format.JSON.Suffix**

A string written after each entry in the output file/stdout defaults to "\n"

**LogWriting.Format.JSON.Pretty**

If true, pretty prints the JSON output (indentation and multi-line). Defaults to false

**LogWriting.Format.JSON.Fields**

A definition of fields defining what is included in each log entry. The structure would be completely user defined but for example:

```json
[
   {
     "Path": "Message",
     "Content": "%m",
     "Type": "string:",
     "Empty": "ZERO"
   },
  {
    "Path": "Meta.Timestamp",
    "Content": "%{02/Jan/2006:15:04:05 Z0700}t",
    "Type": "string:",
    "Empty": "ZERO"
  }
]
```

Would potentially generate an entry in the log file that looks like:

```json
{
  "Message": "Some message",
  "Meta": {
    "Timestamp": "02/Jan/2006:15:04:05 Z0700"
  }
}
```

Each field we want to include needs four pieces of configuration:

### Path
Where in the output JSON the field will be found. If dot-delimited, containing JSON objects will be created.
 
### Content
The value to include in the generated output. Uses the same verbs as defined https://granitic.io/ref/logging-format-output with an addition %m verb to include the log message.

### Type
Optional. The JSON primitive type to try and render the content as. Allowed values are: STRING, NUMBER, BOOL and defaults to STRING

If the content cannot be converted to the required type the Empty value will be used.

### Empty
Optional. If the content is unset or cannot be rendered, this defines how the value is represented in the output JSON. Allowed values are EXCLUDE (do not represent the value), ZERO (use the Golang zero value "", 0, false) or NULL (JSON null)

**Comment by RohitRox** [comment]
> **LogWriting.Format.JSON.Prefix**



> **LogWriting.Format.JSON.Prefix**
> 
> A string written after each entry in the output file/stdout defaults to "\n"

This should be `suffix` ?!  

> **LogWriting.Format.JSON.Fields**

Instead of defining fields, I think it would be simplier
if we could just have default fields
` myLogger.LogInfof("my message")`
logs
`{ level: "info", timestamp: "..", message: "my message" }`
and if someone wants to add additional fields
they should be able to  do 
`myLogger.LogInfof("my message").addFields(map[string]string{"name": "aj", "loc": "ktm"})`
that logs
`{ level: "info", timestamp: "..", message: "my message", name: "aj", loc: "ktm" }`

**Comment by benhalstead** [comment]
So this needs to be backwards compatible with the existing application logging, so changing the runtime Logger interface is out of scope.

Will definitely include a default format that includes all of the log information the default text line formatter includes.

Fixed the typo

**Comment by RohitRox** [comment]
> So this needs to be backwards compatible with the existing application logging, so changing the runtime Logger interface is out of scope.

Ah yes...things are different here (than in Ruby/NodeJs)..I thought the old ones can keep on using `.LogInfof("..")` and new ones can use `.LogInfof("..").addField` which will be added feature But yes it does changes interfaces here. I agree.

**Comment by benhalstead** [comment]
Complete, but implementation quite different to this description. Refer to the Logging and HTTPServer Facility sections of the reference manual.
