### ISSUE TITLE
Installation instructions need updating for go 1.17

### ISSUE THREAD

**Issue by MDUK0001** [graniticio/granitic#65]
Installation instructions don't work for go version 1.17, due to the change in GO111MODULE behaviour. Granitic no longer downloads to $GOPATH/src folder, instead it goes into $GOPATH/pkg folder, unless you run this instead:
`GO111MODULE=off go get github.com/graniticio/granitic`
I also needed some extra steps in the "Testing your installation" step, namely a `go mod download` and a `go get install-test`. 

I'm happy to raise a PR to resolve, but what is the correct way? GO111MODULE=off, or running the install-tools.sh from the pkg directory?

**Comment by benhalstead** [comment]
Thanks for raising this. I'm going to replicate here and give this some thought. If changes are made to the install scripts they need to be backwards compatible with earlier versions of Go.

**Comment by MandipGiri** [comment]
I do agree with @MDUK0001, a new set of instructions is needed as of 1.17 due to the change of download path it now gets downloaded to pkg. So if I may I would suggest adding installation instructions for versions from 1.17 and above as well to clear out the confusion for new users.

**Comment by benhalstead** [comment]
I am working on this now - want to make sure it works for 1.18 as well

**Comment by benhalstead** [comment]
Installation documentation updated
